<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Components\Pages\Mes\**" />
    <Compile Remove="Components\Pages\Security\**" />
    <Content Remove="Components\Pages\Mes\**" />
    <Content Remove="Components\Pages\Security\**" />
    <EmbeddedResource Remove="Components\Pages\Mes\**" />
    <EmbeddedResource Remove="Components\Pages\Security\**" />
    <None Remove="Components\Pages\Mes\**" />
    <None Remove="Components\Pages\Security\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\The365ThingAppLib\The365ThingAppLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Identity.Web" Version="4.10.0" />
  </ItemGroup>

</Project>
